---

- hosts: all
  vars:
    lxc_bridge_address: 10.0.40.1/24
    lxc_dnsmasq_dhcp_range: 10.0.40.2,10.0.40.100,12h
    lxc_dnsmasq_host_record: lxchost.lxc,10.0.40.1

  roles:
  - role: .
    sudo: yes
