---

- template:
    src: dnsmasq.conf
    dest: '{{ lxc_dnsmasq_config_path }}'
  notify: restart networking

- template:
    src: dnsmasq.service
    dest: /etc/systemd/system/{{ lxc_dnsmasq_service_name }}
  when: ansible_os_family == 'Arch'

- service:
    name: '{{ lxc_dnsmasq_service_name }}'
    state: started
    enabled: yes
  when: ansible_os_family == 'Arch'
