---

- include: pacman.yml
  when: ansible_os_family == 'Archlinux'

- include: apt.yml
  when: ansible_os_family == 'Debian'

- include: netctl.yml
  when: ansible_os_family == 'Archlinux'

- include: ifconfig.yml
  when: ansible_os_family == 'Debian'

- include: dnsmasq.yml

- include: sysctl.yml

- include: configure.yml

- include: debian.yml
  when: ansible_os_family == 'Debian'
